### ISSUE TITLE
Random LoginManager logIn Errors

### ISSUE THREAD

**Issue by landonrturner** [facebook/facebook-sdk-swift#286]
# Random LoginManager logIn Errors. Code=308

## Environment

- Xcode Version: `10.0 (10A255)`
- Swift Version: `4.2`
- Installation Platform & Verison: `Carthage` version `0.31.1`
- Using latest facebook/facebook-sdk-swift

## Issue Details

I am getting sporadic `Error Domain=com.facebook.sdk.login Code=308 "(null)"` errors when trying to use the login manager like so:

```swift
let loginManager = LoginManager()

loginManager.logIn(readPermissions: [.publicProfile, .email], viewController: self) { loginResult in
    switch loginResult {
    case .failed(let error):
        print(error)
    case .cancelled:
        print("Facebook Login Cancelled")
    case .success:
        print("Facebook Login Success")
    }
}
```

My initialization code in AppDelegate.swift
```swift
    func application(_ app: UIApplication, open url: URL, options: [UIApplication.OpenURLOptionsKey : Any] = [:]) -> Bool {
        return FBSDKApplicationDelegate.sharedInstance().application(app, open: url, options: options)
    }
```

[There is a similar issue here](https://github.com/facebook/facebook-sdk-swift/issues/51), however, the resolution of enabling keychain sharing in my app did not fix my problem. Retrying logging in eventually works.

**Comment by lemonandlime** [comment]
Im having the exact same Issue and was just gonna post it. To verify that this was a bug I created a clean project and only added the facebook button and the necessary keys in info plist and it fails about 1 out of 4.
Should be easy to reproduce.
This needs to be fixed before I can use the SDK live.

**Comment by bazoooki** [comment]
having the same problem.

**Comment by elad823** [comment]
> same problem.
> 
> Looks like error is FBSDKLoginErrorBadChallengeString.
> 
> The strings differs in one symbol:
> In FBSDKLoginManager.m line 232 - 236.
> challenge received: mH0/43TiAwd 0jyfRil7rkNdnBI=
> challenge expected: mH0/43TiAwd+0jyfRil7rkNdnBI=
> 
> This plus symbol causes the error.
> 
> In FBSDKUtility.m line 65-67.
> 
> ` return [value stringByReplacingOccurrencesOfString:@"+" withString:@" "].stringByRemovingPercentEncoding;`
> 
> Resolution: **challenge received can contain plus symbol**, and URLDecode replaces it with space explicitly. Challenge expected and received are not equal - and that's the reason of error.
> 
> @lostatseajoshua what can be the solution for this bug? Is it: don't send `+` in challenge from FB servers, or don't replace `+` symbol with space in URLDecode method?
> 
> For anyone who wants to fix this issue manually (quick and dirty method), please check the PR: [facebook/facebook-objc-sdk#922](https://github.com/facebook/facebook-objc-sdk/pull/922)

Thanks a lot rinat , that solved the issue.

**Comment by codytwinton** [comment]
This PR shows that the error is in the underlying ObjC SDK: facebook/facebook-objc-sdk#922

Closing this issue for now. Follow along with the mentioned PR for details.

**Comment by kamrankhan07** [comment]
I am still getting this error 1 out of 5 times, on checking I found the following
challengeReceived: RMu4wR/wSbFRzyKk0VfvpvaLs+w=
challengeExpected:RMu4wR/wSbFRzyKk0VfvpvaLs w=
Seems like this time the hotfix is causing issue now, challengeReceived is working with '+'. I am using version 4.39.0

**Comment by kamrankhan07** [comment]
Another example
challengeReceived: t4ZXt4GNj4d0mL++dEzZIk/xLj0=
challengeExpected: t4ZXt4GNj4d0mL  dEzZIk/xLj0=
Looks like someone else from developer team or server side fixed the issue with '+' and its being received correctly now but on client side its causing issue because SDK is replacing '+' with ' '
@rinat-enikeev  @codytwinton

**Comment by kamrankhan07** [comment]
@bptstmlgt please check this [link](https://github.com/AFNetworking/AFNetworking/issues/4279#issuecomment-447108981) 

I was facing another issue stating something like "Software caused connection abort", on checking I found the above link, you can check the description there. I think your issue is most likely this one that I faced. I implemented suggestion A and it works 5/5 times now. 
However I am still not sure about the other issue with challenge string, for now it doesn't happen. I am using the latest sdk from pods without any changes to it. You should also clean your 'derived data' folder after getting the latest pod and before running the code. 
```
    pod 'FacebookSDK', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
    pod 'FBSDKCoreKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
    pod 'FBSDKShareKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
    pod 'FBSDKLoginKit', :git => 'https://github.com/facebook/facebook-objc-sdk.git', :branch => 'master'
```

**Comment by bptstmlgt** [comment]
@kamrankhan07 I just did that indeed, right after my comment (clean build + derived data) and so far the issue is gone. Thanks for the quick answer!

**Comment by ciprian-antal-3PG** [comment]
> I am still getting this error 1 out of 5 times, on checking I found the following
> challengeReceived: RMu4wR/wSbFRzyKk0VfvpvaLs+w=
> challengeExpected:RMu4wR/wSbFRzyKk0VfvpvaLs w=
> Seems like this time the hotfix is causing issue now, challengeReceived is working with '+'. I am using version 4.39.0

Same for me, using version 4.38.1. Any updates on this issue?

**Comment by robtimp** [comment]
@ciprian-antal-3PG It was fixed again in 4.39.1

**Comment by AnthonyUccello** [comment]
I am getting this issue still with 4.39.1 and the most recent sdk (4.4). I get a much higher rate of failure (it works for me maybe 5-10% of the time). I constantly get this error `Error Domain=com.facebook.sdk.login Code=308 "(null)"`

<img width="911" alt="screen shot 2019-03-02 at 12 53 04 pm" src="https://user-images.githubusercontent.com/3809669/53685543-2d356a80-3cea-11e9-98df-ff766a424d5e.png">

**Comment by AnthonyUccello** [comment]
Going down to 4.36.0 seems to have worked. I am now getting consistent Access tokens

**Comment by AnthonyUccello** [comment]
Mind you, the access token is becoming nil as soon as I perform a graph request so I need to file a bug on this.
