### ISSUE TITLE
Have to tap the login button twice for it to work

### ISSUE THREAD

**Issue by dnsbty** [facebook/facebook-sdk-swift#83]
In XCode 8 using Swift 3.0, latest version of the SDK, I have a button set up to handle logins. The first tap it never does anything, but the second it works. Here's the relevant code:

`@IBAction func login(_ sender: UIButton) {
        let loginManager = LoginManager()
        loginManager.logIn([ .publicProfile, .email, .userFriends ], viewController: self) { loginResult in
            switch loginResult {
            case .failed(let error):
                print(error)
            case .cancelled:
                print("User cancelled login.")
            case .success(_, _, let accessToken):
                ...
            }
        }
    }`

I found someone with a similar issue on StackOverflow too: https://stackoverflow.com/questions/39928730/xcode-8-swift-3-facebook-sdk-login-using-loginmanager-have-to-click-twice-to-o

**Comment by thiagoross** [comment]
+1

**Comment by chlkbumper** [comment]
+1

**Comment by xcadaverx** [comment]
Same problem here. Calling from: nil or passing a UIViewController's `self` to the method have the same effect. After the initial 'double-tap' it works as intended until app re-launch.

**Comment by hasgar** [comment]
same issue here..any fix?

**Comment by xcadaverx** [comment]
Seems to me like it is fixed by updating from FBSDKLoginKit and
FBSDKCoreKit pods to FacebookLogin and FacebookCore pods. I've not had the
issue since updating to the newest pods. `pod update`

Cheers,
Daniel

**Comment by aravindkumar** [comment]
same issue

**Comment by FrancisMG** [comment]
Im still having this issue. FBSDKCoreKit (4.34.0)   FBSDKLoginKit (4.34.0)

**Comment by codytwinton** [comment]
@FrancisMG - We're working hard to improve both SDKs, but this appears to be an issue with the iOS Objective-C SDK. Feel free to open a bug report here: https://developers.facebook.com/bugs/
